apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-dns-balanceloader
  namespace: {{.Release.Namespace}}
  labels:
    app: cloudflare-dns-balanceloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-dns-balanceloader
  template:
    metadata:
      labels:
        app: cloudflare-dns-balanceloader
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      serviceAccountName: cloudflare-dns-balanceloader
      containers:
        - name: cloudflare-dns-balanceloader
          image: "datstarkey/cloudflare-dns-loadbalancer:{{ .Chart.Version }}"
          imagePullPolicy: Always
          env:
            - name: CLOUDFLARE_TOKEN
              value: {{.Values.cloudflare.token}}
            - name: CLOUDFLARE_PROXY
              value: {{.Values.cloudflare.proxy | quote|  default "false"}}
