package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            password("env.DockerPassword", "", label = "DockerPassword", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.DockerPassword", "credentialsJSON:1856fa85-f570-4b34-ac19-11a214d302f3", label = "DockerPassword", display = ParameterDisplay.HIDDEN)
        }
        expect {
            password("env.HelmPassword", "", label = "HelmPassword", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.HelmPassword", "credentialsJSON:fe0d17a7-e5e2-4459-8189-e6c23d466f2f", label = "HelmPassword", display = ParameterDisplay.HIDDEN)
        }
    }
}
